### ISSUE TITLE
Problem about install package 

### ISSUE THREAD

**Issue by YIIIII00** [BAREJAA/CBRG#14]
Hello, I encountered some problems when I installed package,
The first time I installed I pressed "run current chunk" to run the whole script, but it stopped at the step "load  package"(line62)
and below it asking if I wanted to install all, I typed "a(all)", and then asking if I wanted to update all,  I also typed "a(all)" 
Then it popped up again if I wanted to update all, so I closed the program.
When I opened it again and tried to reinstall, it showed following error message.
What can I do to solve this install problem?
Thanks for reading my message
![螢幕擷取畫面 2024-04-17 202557](https://github.com/dukecct/CBRG/assets/167316976/4a522092-91fc-4a5a-a947-e2cc5b3f3fb6)

The translation of Chinese：
Error occurred in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]): Loaded namespace 'xfun' 0.42, but required Yes >= 0.43

**Comment by NarainritKaruna** [comment]
"'xfun' 0.42, but required Yes >= 0.43"

**Comment by BAREJAA** [comment]
As the user above has noted, it looks like you need to update your xfun package. Re-install this package, restart your R session, and run the code. Do you still get an error?

**Comment by YIIIII00** [comment]
> As the user above has noted, it looks like you need to update your xfun package. Re-install this package, restart your R session, and run the code. Do you still get an error?
I updated my x fun package, and it worked!
Thanks for helping!

**Comment by BAREJAA** [comment]
Wonderful!
